baseURL = "https://lokal.ninja/thueringen"
languageCode = "de-DE"
title = "Lokal Ninja - Thüringen"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Thüringen"
  repo = "thueringen"
